data:
  path: "/home/alexli/LoLX_ML/training_data"
  
  use_h5: true
  h5_file: "Processed_validate_uncorr.h5"
  x_dataset: "ml_data/X"              # Path to origins data in HDF5 file
  y_dataset: "ml_data/Y"              # Optional: Path to photon ratios for evaluation

model:
  save_path: "/home/alexli/LoLX_ML/training_data/uncorr_model/trained_model_uncorr.keras"

output:
  dir: "/home/alexli/LoLX_ML/plot/"
  # predictions_file: "Y_predictions.npy"  # Will contain photon ratios

visualization:
  num_samples: 3       # Number of samples to visualize
  num_channels: 20     # Number of channels to show in each visualization