data:
  path: "/home/alexli/LoLX_ML/training_data"
  file: "processed_data.h5"
  x_dataset: "ml_data/X"              # Path to origins data in HDF5 file (in ml_data group)
  y_dataset: "ml_data/Y"              # Path to photon ratios data in HDF5 file (in ml_data group) 
  test_size: 0.1                      # Fraction of data to use for testing

model:
  learning_rate: 0.001                # Reduced learning rate for better convergence
  epochs: 100                         # Increased epochs to ensure convergence
  batch_size: 32
  hidden_layers: [64, 128, 256, 128, 64]   # Neural network architecture
  activation: "relu"                  # Activation function
  scale_y: false                      # Don't scale Y since they're already normalized ratios
  use_photon_counts: false            # Set to true if you want to include photon count as an input
  save_path: "/home/alexli/LoLX_ML/training_data/trained_model.keras"

output:
  dir: "/home/alexli/LoLX_ML/training_data"
  save_plots: true                    # Save training plots